#!/bin/bash

i3_config_directory="$HOME/.config/i3"
i3_config_file="$i3_config_directory/config"
i3_includes_file="$i3_config_directory/config.d/i3_configs.conf"

if [[ -f "$i3_includes_file" ]]; then
  [[ -f "$i3_config_file" ]] && rm "$i3_config_file"

  touch "$i3_config_file"

  echo "#### DO NOT EDIT THIS FILE, IT IS GENERATED." >> "$i3_config_file"
  echo "#### EDIT THE FILES HERE: $i3_config_directory/config.d/**/*" >> "$i3_config_file"

  include_file() {
    echo -en "\n#### From file $i3_config_directory/config.d/$1\n" >> "$i3_config_file"
    cat "$i3_config_directory/config.d/$1" >> "$i3_config_file"
    echo -en "\n\n" >> "$i3_config_file"
  }

  get_file_name_from_line () {
    echo $1 | sed "s/import\s*['\"]\(.*\)['\"];*$/\1/"
  }

  IFS="$(echo -en '\n\r')"

  for config_line in $(cat $i3_includes_file)
  do
    if [ -n $config_line ]; then
      if [ "${config_line:0:7}" == "import " ]; then
        file_name="$(get_file_name_from_line $config_line)"
        include_file "$file_name"
      fi
    fi
  done

  if [[ "$1" == "restart" || "$1" == "reload" ]]; then
    i3-msg "$1"
  fi
else
  echo "ERROR:"
  echo "Please create the configs import file:"
  echo " $i3_config_directory/config.d/i3_configs.conf"
fi
